### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by ivangabriele** [MTES-MCT/monitorenv#967]
## Reproduction:

1. Ouvrir la liste de unités (sur la carte)
2. Cliquer sur une unité pour ouvrir sa fiche
3. Cliquer sur "Ajouter un contact"
4. Cliquer sur le select "Nom du contact" pour l'ouvrir

## Erreur :

```
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:245690:58)
    at http://localhost:3000/static/js/bundle.js:245709:7
    at deliverResizeLoopError (http://localhost:3000/static/js/bundle.js:63125:10)
    at process (http://localhost:3000/static/js/bundle.js:63350:95)
    at http://localhost:3000/static/js/bundle.js:63493:80
```

## Explication

Il s'agit d'une erreur provenant de Rsuite avec deux issues intéressantes :

- Une côté Rsuite: rsuite/rsuite#3180, toujours ouverte.
- Une ouverte sur la libraire d'origine : juggle/resize-observer#103.

Il ne s'agit à priori pas d'un bug mais d'une réelle erreur bien détectée par la librairie d'origine : un second resize event envoyé alors que la notification du premier est encore en cours d'envoi : https://github.com/juggle/resize-observer/blob/master/README.md#resize-loop-detection.

Un des core contributeurs de Rsuite suggère d'ignorer cette erreur, ce qui ne paraît pas recommandable (comme le développeur de `juggle/resize-observer` l'explique) puisque cela va simplement masquer un bug bien réel.

Une solution plus propre que d'ignorer – mais pas idéale – serait peut-être de wrapper les observers dans un `window.setImmediate()` [[1](https://github.com/juggle/resize-observer/issues/103#issuecomment-1711148285)]. Un autre, plus subjective, serait de debouncer.

**Comment by ivangabriele** [comment]
Ping @claire2212 @thoomasbro @louptheron si vous avez des suggestions.
